GPC header rule
duckduckgo/ddg2dnr pull request #38
Opened 2022-11-15 15:17 UTC by jdorweiler

Adds a modify header rule to add GPC to all requests. 
- https://privacy-test-pages.glitch.me/privacy-protections/gpc/

2022-11-15 17:05 UTC, kzar requested changes

2022-11-15 17:05 UTC, kzar commented on lib/rulePriorities.js
> +exports.GPC_HEADER_PRIORITY = 20000
This should be exported from the lib/gpc.js module instead.

2022-11-15 17:05 UTC, kzar commented on test/gpc.js
> +const expectedGPCRule = [{
Maybe call it result, since it includes the lookup too?
```suggestion
const expectedGPCResult = [{
```

2022-11-15 17:05 UTC, kzar commented on test/gpc.js
> +                domain: 'content-blocking1.example',
Maybe change the domain so it's clear it's unrelated to contentBlocking allowlist? (Same below.)
```suggestion
                domain: 'exception1.example',
```

2022-11-15 17:05 UTC, kzar commented on test/gpc.js
> +const assert = require('assert')
Please could you add a test for the relative rule priorities of `GPC_HEADER_PRIORITY` in `test/rulePrioirities.js` too?

2022-11-15 19:36 UTC, jdorweiler commented on lib/gpc.js
> +    const rule = baseHeaderRule
I made a copy of the rule instead. `generateDNRRule` assume that you have always have `requestDomains` and fixing it was getting messy.

2022-11-16 17:51 UTC, kzar commented on package.json
> +        "eslint-fix": "npm run eslint -- --fix",
Nit: Mind putting this one below the "eslint" entry?

2022-11-16 17:52 UTC, kzar submitted a review, later dismissed

2022-11-16 18:10 UTC, kzar approved these changes

2022-11-16 18:10 UTC, merged